### ISSUE TITLE
Jonathan Carter

### ISSUE THREAD

**Issue by ABN-Askham** [placeposition/alpaka-user-group#2]
There is a duplicated entry for Jonathan Carter. Not sure why? Is this is system issue or have we double entered? Is there a way that the system apply a sense check where a team member name is entered that matches the name of another?

**Comment by placeposition** [comment]
Users have to be unique by their email address, it doesn't check and refuse new team members by their names. I can see Jonathan has two different email addresses - one is surely a typo of the other. The mobile numbers are also similar but different, but we don't check for uniqueness on mobiles.

You can make either one inactive but check their schedules first since there might be shifts or events relevant to Jonathan.
