### ISSUE TITLE
Edit presence issues

### ISSUE THREAD

**Issue by BetterFoodHR** [placeposition/alpaka-user-group#23]
- 'NULL' issue keeps happening when the store managers add someones presence manually (only doesn't happen with me?)
- Edit payable duration often reverts back to previous once you press 'submit' - highly irritating for the managers :( 
- Often the total presence is 1 minute out due to it counting the seconds but then it's very difficult to amend as we can't see/edit the seconds - can we either not include the seconds in the total or have eyes on them?
- is there any way we can get it to reject a PIN it doesn't recognise? to minimise the incorrect clocks?

**Comment by placeposition** [comment]
Presence V2 *FIXED*

We cant reject PINS at the device- the device has no idea and doesn't check them because there is a legitimate use case to accept PIN that arent genuine ....YET. You can use presence to clock in and out visitors or new staff by inviting them to pick their own PIn and just getting started- you will see the results even before Alpaka understands them.
