### ISSUE TITLE
Why does the system opens extra tabs all the time

### ISSUE THREAD

**Issue by KateRodgers** [placeposition/alpaka-user-group#49]
Management request

**Comment by placeposition** [comment]
It opens extra tabs deliberately in 3 places. 

![Screenshot 2020-10-18 at 18 35 23](https://user-images.githubusercontent.com/4497319/96375388-b3791b80-1170-11eb-9e4d-6ab44f6a21a2.png)

this is the most obvious action that opens a new tab - the Schedule Icon will take you to a wall planner version of the schedule which is all the staff for up to 4 weeks.

The other two locations that prompt a new tab are both for Presence 

![Screenshot 2020-10-18 at 18 37 13](https://user-images.githubusercontent.com/4497319/96375446-f63af380-1170-11eb-840f-45ac444be990.png)

The pages that prompt it are lists of the Team - the list pages are there for fast and efficient access to the individual's Presence records- if the page navigated away from the list to the individual you would have no systematic method for going down the list and making sure you check everyone. The user-bullseye icon you see will open a single new tab for that person- you can then check or edit their presence readings and simply switch your tab back to the list - 

you do not need to close the second tab because......

If you then click the next team member's bullseye icon it will use the tab you already have open to show you their results - so you operate on a maximum of 2 tabs.
